-- Create the table for storing real-time train positions
CREATE TABLE IF NOT EXISTS realtime_train_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subway_line_id VARCHAR(50),
    subway_line_name VARCHAR(50),
    station_id VARCHAR(50),
    station_name VARCHAR(50),
    train_number VARCHAR(50),
    last_received_at TIMESTAMPTZ,
    received_at TIMESTAMPTZ,
    up_down_type INTEGER, -- 0: Up/Inner, 1: Down/Outer
    terminal_station_id VARCHAR(50),
    terminal_station_name VARCHAR(50),
    train_status INTEGER, -- 0:Entry, 1:Arrive, 2:Depart, 3:Pre-depart
    is_express INTEGER, -- 0:No, 1:Express, 7:Special
    is_last_train BOOLEAN,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster analysis
CREATE INDEX IF NOT EXISTS idx_train_positions_created_at ON realtime_train_positions(created_at);
CREATE INDEX IF NOT EXISTS idx_train_positions_line_station ON realtime_train_positions(subway_line_id, station_id);
